### ISSUE TITLE
How to pay money to some one directly?

### ISSUE THREAD

**Issue by wutieguo** [square/in-app-payments-ios-quickstart#6] opened 2019-03-11 06:04 UTC
I am going to build the Barber app.  
I want the customer to pay money to barber directly on my app.  
how can I integrate Square SDK?
what is transfer API?

**Comment by StephenJosey** [comment] 2019-03-11 15:14
Duplicate of: https://github.com/square/in-app-payments-ios/issues/5 closing for now since I responded to the other issue.

**Closed by StephenJosey** 2019-03-11 15:14 UTC
